type_map: dict = {
    "VARCHAR": "string",
    "VARBINARY": "binary",
    "TINYINT": "byte",
    "TIMESTAMP": "timestamp",
    "TIME": "date",
    "SMALLINT": "short",
    "REAL": "double",
    "NUMERIC": "double",
    "LONGVARCHAR": "string",
    "JAVA_OBJECT": "object",
    "INTEGER": "int",
    "FLOAT": "float",
    "DOUBLE": "double",
    "DECIMAL": "big_decimal",
    "DATE": "date",
    "CLOB": "string",
    "CHAR": "string",
    "BOOLEAN": "boolean",
    "BLOB": "binary",
    "BIT": "byte",
    "BINARY": "binary",
    "BIGINT": "big_integer",

    # BELOW IS NOT PRESENT IN THE FIRST PLACE
    "SERIAL": "int",
    "BPCHAR": "string",
    "INT4": "int",
    "INT2": "int",
    "BOOL": "int",
    "TEXT": "int",
    "BYTEA": "byte",
}
